/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as TaxIndexRouteImport } from './routes/tax/index'
import { Route as SuperIndexRouteImport } from './routes/super/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as LoansIndexRouteImport } from './routes/loans/index'
import { Route as BudgetIndexRouteImport } from './routes/budget/index'
import { Route as AccountsIndexRouteImport } from './routes/accounts/index'
import { Route as TransactionsNewRouteImport } from './routes/transactions/new'
import { Route as TaxYearRouteImport } from './routes/tax/$year'
import { Route as SuperCalculatorRouteImport } from './routes/super/calculator'
import { Route as PortfolioIdRouteImport } from './routes/portfolio/$id'
import { Route as LoansCalculatorRouteImport } from './routes/loans/calculator'
import { Route as LoansIdRouteImport } from './routes/loans/$id'
import { Route as BudgetForecastRouteImport } from './routes/budget/forecast'
import { Route as AccountsIdRouteImport } from './routes/accounts/$id'
import { Route as SuperResearchIndexRouteImport } from './routes/super/research/index'
import { Route as SuperAnalysisIndexRouteImport } from './routes/super/analysis/index'
import { Route as SuperResearchPapersRouteImport } from './routes/super/research/papers'
import { Route as SuperResearchFeesRouteImport } from './routes/super/research/fees'
import { Route as SuperResearchAllocationsRouteImport } from './routes/super/research/allocations'
import { Route as SuperAnalysisProjectionsRouteImport } from './routes/super/analysis/projections'
import { Route as SuperAnalysisHistoricalRouteImport } from './routes/super/analysis/historical'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxIndexRoute = TaxIndexRouteImport.update({
  id: '/tax/',
  path: '/tax/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperIndexRoute = SuperIndexRouteImport.update({
  id: '/super/',
  path: '/super/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansIndexRoute = LoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetIndexRoute = BudgetIndexRouteImport.update({
  id: '/budget/',
  path: '/budget/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsNewRoute = TransactionsNewRouteImport.update({
  id: '/transactions/new',
  path: '/transactions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxYearRoute = TaxYearRouteImport.update({
  id: '/tax/$year',
  path: '/tax/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperCalculatorRoute = SuperCalculatorRouteImport.update({
  id: '/super/calculator',
  path: '/super/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIdRoute = PortfolioIdRouteImport.update({
  id: '/portfolio/$id',
  path: '/portfolio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansCalculatorRoute = LoansCalculatorRouteImport.update({
  id: '/loans/calculator',
  path: '/loans/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansIdRoute = LoansIdRouteImport.update({
  id: '/loans/$id',
  path: '/loans/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetForecastRoute = BudgetForecastRouteImport.update({
  id: '/budget/forecast',
  path: '/budget/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIdRoute = AccountsIdRouteImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperResearchIndexRoute = SuperResearchIndexRouteImport.update({
  id: '/super/research/',
  path: '/super/research/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAnalysisIndexRoute = SuperAnalysisIndexRouteImport.update({
  id: '/super/analysis/',
  path: '/super/analysis/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperResearchPapersRoute = SuperResearchPapersRouteImport.update({
  id: '/super/research/papers',
  path: '/super/research/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperResearchFeesRoute = SuperResearchFeesRouteImport.update({
  id: '/super/research/fees',
  path: '/super/research/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperResearchAllocationsRoute =
  SuperResearchAllocationsRouteImport.update({
    id: '/super/research/allocations',
    path: '/super/research/allocations',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuperAnalysisProjectionsRoute =
  SuperAnalysisProjectionsRouteImport.update({
    id: '/super/analysis/projections',
    path: '/super/analysis/projections',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuperAnalysisHistoricalRoute = SuperAnalysisHistoricalRouteImport.update({
  id: '/super/analysis/historical',
  path: '/super/analysis/historical',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/budget/forecast': typeof BudgetForecastRoute
  '/loans/$id': typeof LoansIdRoute
  '/loans/calculator': typeof LoansCalculatorRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/super/calculator': typeof SuperCalculatorRoute
  '/tax/$year': typeof TaxYearRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/accounts/': typeof AccountsIndexRoute
  '/budget/': typeof BudgetIndexRoute
  '/loans/': typeof LoansIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/super/': typeof SuperIndexRoute
  '/tax/': typeof TaxIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/super/analysis/historical': typeof SuperAnalysisHistoricalRoute
  '/super/analysis/projections': typeof SuperAnalysisProjectionsRoute
  '/super/research/allocations': typeof SuperResearchAllocationsRoute
  '/super/research/fees': typeof SuperResearchFeesRoute
  '/super/research/papers': typeof SuperResearchPapersRoute
  '/super/analysis/': typeof SuperAnalysisIndexRoute
  '/super/research/': typeof SuperResearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/budget/forecast': typeof BudgetForecastRoute
  '/loans/$id': typeof LoansIdRoute
  '/loans/calculator': typeof LoansCalculatorRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/super/calculator': typeof SuperCalculatorRoute
  '/tax/$year': typeof TaxYearRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/accounts': typeof AccountsIndexRoute
  '/budget': typeof BudgetIndexRoute
  '/loans': typeof LoansIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/super': typeof SuperIndexRoute
  '/tax': typeof TaxIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/super/analysis/historical': typeof SuperAnalysisHistoricalRoute
  '/super/analysis/projections': typeof SuperAnalysisProjectionsRoute
  '/super/research/allocations': typeof SuperResearchAllocationsRoute
  '/super/research/fees': typeof SuperResearchFeesRoute
  '/super/research/papers': typeof SuperResearchPapersRoute
  '/super/analysis': typeof SuperAnalysisIndexRoute
  '/super/research': typeof SuperResearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/budget/forecast': typeof BudgetForecastRoute
  '/loans/$id': typeof LoansIdRoute
  '/loans/calculator': typeof LoansCalculatorRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/super/calculator': typeof SuperCalculatorRoute
  '/tax/$year': typeof TaxYearRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/accounts/': typeof AccountsIndexRoute
  '/budget/': typeof BudgetIndexRoute
  '/loans/': typeof LoansIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/super/': typeof SuperIndexRoute
  '/tax/': typeof TaxIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/super/analysis/historical': typeof SuperAnalysisHistoricalRoute
  '/super/analysis/projections': typeof SuperAnalysisProjectionsRoute
  '/super/research/allocations': typeof SuperResearchAllocationsRoute
  '/super/research/fees': typeof SuperResearchFeesRoute
  '/super/research/papers': typeof SuperResearchPapersRoute
  '/super/analysis/': typeof SuperAnalysisIndexRoute
  '/super/research/': typeof SuperResearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts/$id'
    | '/budget/forecast'
    | '/loans/$id'
    | '/loans/calculator'
    | '/portfolio/$id'
    | '/super/calculator'
    | '/tax/$year'
    | '/transactions/new'
    | '/accounts/'
    | '/budget/'
    | '/loans/'
    | '/portfolio/'
    | '/settings/'
    | '/super/'
    | '/tax/'
    | '/transactions/'
    | '/super/analysis/historical'
    | '/super/analysis/projections'
    | '/super/research/allocations'
    | '/super/research/fees'
    | '/super/research/papers'
    | '/super/analysis/'
    | '/super/research/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts/$id'
    | '/budget/forecast'
    | '/loans/$id'
    | '/loans/calculator'
    | '/portfolio/$id'
    | '/super/calculator'
    | '/tax/$year'
    | '/transactions/new'
    | '/accounts'
    | '/budget'
    | '/loans'
    | '/portfolio'
    | '/settings'
    | '/super'
    | '/tax'
    | '/transactions'
    | '/super/analysis/historical'
    | '/super/analysis/projections'
    | '/super/research/allocations'
    | '/super/research/fees'
    | '/super/research/papers'
    | '/super/analysis'
    | '/super/research'
  id:
    | '__root__'
    | '/'
    | '/accounts/$id'
    | '/budget/forecast'
    | '/loans/$id'
    | '/loans/calculator'
    | '/portfolio/$id'
    | '/super/calculator'
    | '/tax/$year'
    | '/transactions/new'
    | '/accounts/'
    | '/budget/'
    | '/loans/'
    | '/portfolio/'
    | '/settings/'
    | '/super/'
    | '/tax/'
    | '/transactions/'
    | '/super/analysis/historical'
    | '/super/analysis/projections'
    | '/super/research/allocations'
    | '/super/research/fees'
    | '/super/research/papers'
    | '/super/analysis/'
    | '/super/research/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsIdRoute: typeof AccountsIdRoute
  BudgetForecastRoute: typeof BudgetForecastRoute
  LoansIdRoute: typeof LoansIdRoute
  LoansCalculatorRoute: typeof LoansCalculatorRoute
  PortfolioIdRoute: typeof PortfolioIdRoute
  SuperCalculatorRoute: typeof SuperCalculatorRoute
  TaxYearRoute: typeof TaxYearRoute
  TransactionsNewRoute: typeof TransactionsNewRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  BudgetIndexRoute: typeof BudgetIndexRoute
  LoansIndexRoute: typeof LoansIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SuperIndexRoute: typeof SuperIndexRoute
  TaxIndexRoute: typeof TaxIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
  SuperAnalysisHistoricalRoute: typeof SuperAnalysisHistoricalRoute
  SuperAnalysisProjectionsRoute: typeof SuperAnalysisProjectionsRoute
  SuperResearchAllocationsRoute: typeof SuperResearchAllocationsRoute
  SuperResearchFeesRoute: typeof SuperResearchFeesRoute
  SuperResearchPapersRoute: typeof SuperResearchPapersRoute
  SuperAnalysisIndexRoute: typeof SuperAnalysisIndexRoute
  SuperResearchIndexRoute: typeof SuperResearchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax/': {
      id: '/tax/'
      path: '/tax'
      fullPath: '/tax/'
      preLoaderRoute: typeof TaxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/': {
      id: '/super/'
      path: '/super'
      fullPath: '/super/'
      preLoaderRoute: typeof SuperIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/': {
      id: '/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof LoansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget/': {
      id: '/budget/'
      path: '/budget'
      fullPath: '/budget/'
      preLoaderRoute: typeof BudgetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/new': {
      id: '/transactions/new'
      path: '/transactions/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof TransactionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax/$year': {
      id: '/tax/$year'
      path: '/tax/$year'
      fullPath: '/tax/$year'
      preLoaderRoute: typeof TaxYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/calculator': {
      id: '/super/calculator'
      path: '/super/calculator'
      fullPath: '/super/calculator'
      preLoaderRoute: typeof SuperCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$id': {
      id: '/portfolio/$id'
      path: '/portfolio/$id'
      fullPath: '/portfolio/$id'
      preLoaderRoute: typeof PortfolioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/calculator': {
      id: '/loans/calculator'
      path: '/loans/calculator'
      fullPath: '/loans/calculator'
      preLoaderRoute: typeof LoansCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/$id': {
      id: '/loans/$id'
      path: '/loans/$id'
      fullPath: '/loans/$id'
      preLoaderRoute: typeof LoansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget/forecast': {
      id: '/budget/forecast'
      path: '/budget/forecast'
      fullPath: '/budget/forecast'
      preLoaderRoute: typeof BudgetForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$id': {
      id: '/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AccountsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/research/': {
      id: '/super/research/'
      path: '/super/research'
      fullPath: '/super/research/'
      preLoaderRoute: typeof SuperResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/analysis/': {
      id: '/super/analysis/'
      path: '/super/analysis'
      fullPath: '/super/analysis/'
      preLoaderRoute: typeof SuperAnalysisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/research/papers': {
      id: '/super/research/papers'
      path: '/super/research/papers'
      fullPath: '/super/research/papers'
      preLoaderRoute: typeof SuperResearchPapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/research/fees': {
      id: '/super/research/fees'
      path: '/super/research/fees'
      fullPath: '/super/research/fees'
      preLoaderRoute: typeof SuperResearchFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/research/allocations': {
      id: '/super/research/allocations'
      path: '/super/research/allocations'
      fullPath: '/super/research/allocations'
      preLoaderRoute: typeof SuperResearchAllocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/analysis/projections': {
      id: '/super/analysis/projections'
      path: '/super/analysis/projections'
      fullPath: '/super/analysis/projections'
      preLoaderRoute: typeof SuperAnalysisProjectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/analysis/historical': {
      id: '/super/analysis/historical'
      path: '/super/analysis/historical'
      fullPath: '/super/analysis/historical'
      preLoaderRoute: typeof SuperAnalysisHistoricalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsIdRoute: AccountsIdRoute,
  BudgetForecastRoute: BudgetForecastRoute,
  LoansIdRoute: LoansIdRoute,
  LoansCalculatorRoute: LoansCalculatorRoute,
  PortfolioIdRoute: PortfolioIdRoute,
  SuperCalculatorRoute: SuperCalculatorRoute,
  TaxYearRoute: TaxYearRoute,
  TransactionsNewRoute: TransactionsNewRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  BudgetIndexRoute: BudgetIndexRoute,
  LoansIndexRoute: LoansIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SuperIndexRoute: SuperIndexRoute,
  TaxIndexRoute: TaxIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
  SuperAnalysisHistoricalRoute: SuperAnalysisHistoricalRoute,
  SuperAnalysisProjectionsRoute: SuperAnalysisProjectionsRoute,
  SuperResearchAllocationsRoute: SuperResearchAllocationsRoute,
  SuperResearchFeesRoute: SuperResearchFeesRoute,
  SuperResearchPapersRoute: SuperResearchPapersRoute,
  SuperAnalysisIndexRoute: SuperAnalysisIndexRoute,
  SuperResearchIndexRoute: SuperResearchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
